version: '3.8'

services:
  youtube-transcriber:
    build: .
    ports:
      - "4000:4000"
    volumes:
      # Cookies klasörünü volume olarak bağla
      - ./cookies:/app/cookies:ro
      # Screenshots klasörünü volume olarak bağla (opsiyonel)
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
