version: '3.8'

services:
  youtube-transcriber:
    image: digisfer/youtube-transcriber:latest
    ports:
      - "5000:5000"
    volumes:
      # Mount cookies directory for YouTube authentication
      - ./cookies:/app/cookies:ro
      # Mount screenshots directory for captured images
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
